### ISSUE TITLE
Use GRCh38 

### ISSUE THREAD

**Issue by Luis20N** [ding-lab/hotspot3d#13]
Hello,

I would like to use the new transcripts for GRCh38, do you know if it is possible by changing in the Trans.pm the download path or I would need more changes?

Thank you

**Comment by AdamDS** [comment]
I think that we can just add input options to the trans step to allow a user to define the GRCh version and release. I've looked at the URL paths and they follow an easy pattern for specified GRCh & release. I'm currently testing out an update that will allow any release since Ensembl 55, covering GRCh 37 & 38. I should have an update sometime in the next few days.

**Comment by Luis20N** [comment]
That would be great! Thanks so much for your help.
