### ISSUE TITLE
Summary Bug

### ISSUE THREAD

**Issue by Luis20N** [ding-lab/hotspot3d#14]
Hi,

When I try to use the summary command with a cluster file, it raises me the following error  "Not a valid clusters file!". I think it's because of the column "Weight" that in the previous versions was called "Recurrence", because when I only change the name Weight to Recurrence I can normally run the command.

```
sub readClustersFile {
	my ( $this ) = @_;
	my $infh = new FileHandle;
	unless( $infh->open( $this->{'clusters_file'} , "r" ) ) { die "Could not open clusters file $! \n" };
	my @cols;
	while ( my $line = <$infh> ) {
		chomp( $line );
		if ( $line =~ /^Cluster/ ) {
			my $i = 0;
			my %cols = map{ ( $_ , $i++ ) } split( /\t/ , $line );
			unless( defined( $cols{"Cluster"} )
				and defined( $cols{"Gene/Drug"} )
				and defined( $cols{"Mutation/Gene"} )
				and defined( $cols{"Degree_Connectivity"} )
				and defined( $cols{"Closeness_Centrality"} )
				and defined( $cols{"Geodesic_From_Centroid"} )
				and defined( $cols{"Recurrence"} ) ) {
				die "Not a valid clusters file!\n";
```

Thanks for the work.

Best,
Luís Nunes

**Comment by amilacsw** [comment]
Hi Luís,
Thanks so much for letting us know about the bug. As you have correctly identified, the bug is from the new format of the header in the clusters file. We have fixed the bug (v1.3.1) so that, now both the header formats are identified by the Summary module. Please do not hesitate to let us know if you noticed any other bugs.

Best,
Amila
